### ISSUE TITLE
Error occure "this.api.asc_OnSaveEnd is not a function"

### ISSUE THREAD

**Issue by sunlad1** [ONLYOFFICE/document-editor-vue#23]
I want save file with the js code, so I use next method:
`editor.processSaveResult(true, 'Your document has been saved.');`

but, it occure error. the document server log show this
`[2023-07-30T06:20:57.754] [ERROR] [localhost] [862f4ea9442147168bdfa5a07d14dfc9] [22] nodeJS - clientLog: changesError: Error: Uncaught TypeError: this.api.asc_OnSaveEnd is not a function
 Script: http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js
 Line: 8:2463672
 userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
 platform: Win32
 isLoadFullApi: true
 isDocumentLoadComplete: true
 performance.memory: {"totalJSHeapSize":217741268,"usedJSHeapSize":204639936,"jsHeapSizeLimit":4294705152}
 StackTrace: TypeError: this.api.asc_OnSaveEnd is not a function
    at i.onProcessSaveResult (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:2463672)
    at D (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:97744)
    at Object.<anonymous> (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:97948)
    at Object.<anonymous> (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:91123)
    at Object.<anonymous> (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:177672)
    at Object.dispatch (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:43421)
    at b.handle (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:41416)
    at Object.trigger (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:71941)
    at Object.<anonymous> (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:72537)
    at Function.each (http://office.k8s-test.clps.com.cn/7.4.0-163/web-apps/apps/spreadsheeteditor/main/app.js:8:2978)` 

here is my code sample

`<template>
  <DocumentEditor
	id="docEditor"
	:config="config"
	:documentServerUrl="serverUrl"
	:events_on-app-ready="appReady"
	height="1020px"
  />
</template>

<script setup>
import {defineExpose, defineProps, onMounted, ref} from 'vue';
import {DocumentEditor} from "@onlyoffice/document-editor-vue";
import pageApi from '../../assets/api/page.js'

const serverUrl = import.meta.env.VITE_OFFICE_SERVER + "";

const props = defineProps({
  content: {
	type: String,
	required: true,
	default: '',
  }
});
let content;
let config;
let editor;
if (props.content) {
  content = JSON.parse(props.content);
  config = ref(content);
}
let appReady = (docEditor) => {
  editor = docEditor
}
let save = () => {
  debugger
  editor.processSaveResult(true, 'Your document has been saved.');
}
onMounted(() => {
  pageApi.getOfficeToken(content).then((token) => {
	config.value.token = token.data
  });
});
defineExpose({save});
</script>`
the moule version is 1.3.0
how can i fix it, hope help from somebody!

**Comment by SergeyKorneyev** [comment]
Could you specify what the `processSaveResult` method is, where you got the information about it and what is the goal of using it?
